manipulator:
  #kinematics_solver: abb_irb1200_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.05
